# -*- coding: utf-8 -*-
"""activation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuFsiIFcd4x3xfIHSRD-4jyW7GtartQh
"""

import numpy as n
import matplotlib.pyplot as pt
def sigmoid(x):
  return 1/(1+n.exp(-x))
x = n.linspace(-10,10,249)
pt.plot(x,sigmoid(x))
pt.axis('tight')
pt.title('Sigmoid')
pt.show()

def tanh(x):
  return n.tanh(x)
pt.plot(x,tanh(x))
pt.title("tanh")
pt.show()

def ReLU(x):
  a=[]
  for i in x:
    if(i<0):
      a.append(0)
    else:
      a.append(i)
  return a;
pt.plot(x,ReLU(x))
pt.title('ReLU')
pt.show()