# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1boqvb3_uR7kkBiR-aAV4IH3JanivsNeM
"""

import matplotlib.pyplot as pt
import numpy as n
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris=load_iris()

iris.data[:4]

iris.feature_names

iris.target

print(iris.target_names)

print(type(iris.data))
print(type(iris.target))

iris.data.shape

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=41)

X_train.shape, X_test.shape

y_train.shape, y_train.shape

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

knn.score(X_train, y_train), knn.score(X_test, y_test)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(knn.score(X_train, y_train), knn.score(X_test, y_test))

confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))