# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n-E4oGzUHtjx4ZxKmWFHzBY7f_-Ke73S
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as pt
import pandas as p
import numpy as n
import seaborn as sb
# %matplotlib inline

from sklearn.datasets import load_breast_cancer

a = load_breast_cancer()

a.keys()

print(a['DESCR'])

b = pd.DataFrame(a['data'],columns=a['feature_names'])

b.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(b)

scaled_data = scaler.transform(b)

from sklearn.decomposition import PCA

pca = PCA(n_components=3)
pca.fit(scaled_data)

x_pca = pca.transform(scaled_data)

scaled_data.shape

x_pca.shape

pt.figure(figsize=(8,6))
pt.scatter(x_pca[:,0],x_pca[:,1],c=a['target'],cmap='plasma')
pt.xlabel('First principal component')
pt.ylabel('Second Principal Component')

pca.components_